name: find_gghosts

on:
  schedule:
    - cron: "11 6 * * *"

jobs:
  ping-ip-addresses:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Installed package list
        run: apt list --installed
        
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
        
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
        
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Ping IP and save hosts
        run: python gghosts.py
